# Generated by Django 3.2 on 2025-09-03 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquiteto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('especialidade', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone_principal', models.CharField(max_length=20)),
                ('telefone_secundario', models.CharField(blank=True, max_length=20)),
                ('nome_secundario', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_imovel', models.CharField(choices=[('Residência', 'Residência'), ('Condomínio', 'Condomínio'), ('Outro', 'Outro')], max_length=20)),
                ('nome_condominio', models.CharField(blank=True, max_length=100)),
                ('nome_estabelecimento', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateTimeField()),
                ('local', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('arquiteto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.arquiteto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas_pendentes', models.IntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proxima_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('Em dia', 'Em dia'), ('Atrasado', 'Atrasado'), ('Quitado', 'Quitado')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(max_length=100)),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluída', 'Concluída'), ('Pausada', 'Pausada')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('arquiteto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.arquiteto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
