# Generated by Django 3.2 on 2025-09-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_visita_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='Obra',
            field=models.CharField(default='ADCIONE O NOME DA OBRA', max_length=200),
        ),
        migrations.AlterField(
            model_name='obra',
            name='tipo_servico',
            field=models.CharField(max_length=300),
        ),
    ]
