# Generated by Django 3.2 on 2025-09-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250905_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='Obra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.obra'),
        ),
    ]
