# Generated by Django 3.2 on 2025-09-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pagamento_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='Obra',
            field=models.CharField(default='ADCIONE O NOME DA OBRA', max_length=500),
        ),
    ]
