# Generated by Django 3.2 on 2025-09-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_obra_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='Obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.obra'),
        ),
    ]
