# Generated by Django 3.2 on 2025-09-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_pagamento_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='cliente',
        ),
    ]
