# Generated by Django 3.2 on 2025-09-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_pagamento_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='Obra',
            new_name='obra',
        ),
    ]
