# Generated by Django 3.2 on 2025-09-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_obra_pagamento_obra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='obra',
            new_name='Nome_Obra',
        ),
    ]
