# Generated by Django 3.2 on 2025-09-06 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_obra_pagamento_nome_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
    ]
