# Generated by Django 3.2 on 2025-09-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_pagamento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='----', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='01001-000', max_length=9),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='----', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='----', max_length=200),
        ),
    ]
